select * from customer_behaviour;
--- What is the total revenue generated by male vs female customers?

select gender,sum(purchase_amount_usd) from customer_behaviour
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount_usd from customer_behaviour
where discount_applied = 'Yes' and purchase_amount_usd >= 
(select avg(purchase_amount_usd) from customer_behaviour);


-- What are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating)::numeric,2) from customer_behaviour
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average purchase amount between standard and express shipping.

select round(avg(purchase_amount_usd)::numeric,2),shipping_type
from customer_behaviour
where shipping_type in ('Standard','Express')
group by shipping_type;

-- The subscribed customers spent more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
round(avg(purchase_amount_usd)::numeric,2) as average_purchase_amount ,
sum(purchase_amount_usd) as total_purchase_amount
from customer_behaviour
group by subscription_status
order by average_purchase_amount desc;

-- Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, 

round(100 * sum(case when discount_applied = 'Yes' then 1
		  else 0
	end )/ count(*)::numeric,2) as percentage_of_discout_applied

from customer_behaviour
group by item_purchased
order by percentage_of_discout_applied desc
limit 5;

-- Segment customers into new, returning, and loyal based on their total number of previous purchases 
--and show the count of each segment.

with customer_segment as(
select customer_id, 
case 
	when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_type
from customer_behaviour)

select customer_type,count(*) as count_of_customers from customer_segment
group by customer_type
order by count_of_customers desc;


-- What are the top 3 most purchased products within each category?

with count_of_product_purchase as (
select item_purchased,category,
count(*) as number_of_purchases,
row_number() over (partition by category 
					order by count(previous_purchases) desc) as row_num

from customer_behaviour
group by item_purchased,category)

select item_purchased, category, number_of_purchases,row_num
from count_of_product_purchase
where row_num<=3;

-- Customers who are repeat buyers (for more than 5 previous purchases) are also likely to subscribe?

select subscription_status, count(*) as repeat_buyers
from customer_behaviour
where previous_purchases > 5
group by subscription_status;

-- What is the revenue contribution of each age group?

select age_group, sum(purchase_amount_usd) as revenue_contribution
from customer_behaviour
group by age_group
order by revenue_contribution desc;





